### PR TITLE
Corrections for Pull request #3

### PR DESCRIPTION
**Pull request by mrpetro**
All changed according to code review

### CODE REVIEW

**Comment by gbaychev** [comment]
Thank you, mate, I've merged your changes. Cheers. 🤘

**Comment by mrpetro** [comment]
No problem, those were good remarks, I'm was a bit sloppy.
And I actually had no idea how to do corrections to Pull Request, so I've guessed it, still not sure if creating separate pull request is the correct thing to do, or there is different mechanism here.

**Comment by gbaychev** [comment]
Don't worry. I don't know either since I'm not getting that much pull requests. We've managed to get your changes in the source tree, so all is good. 

Happy holidays. :)

**Comment by AndreasPK** [comment]
Just commiting on the same branch should be enough: [Link](https://stackoverflow.com/questions/9790448/how-to-update-a-pull-request-from-forked-repo)

**Pull request merged**
