### PR TITLE
Improved dialogs

### PR DESCRIPTION
**Pull request by Baltasarq**
This is a modification of two dialogs that needed more size and better placement.

- OptionsDialog: Needed more size and more minimum size.
- PDFExportOptions: Needed more size and ok/cancel buttons relocation.

options_dialog
pdf_export_options_dialog

## PDFExportOptions:
- Relocation of buttons was done in the designer (PDFExportOptions.Designer.cs), but the resizing was done in the PDFExportOptions.cs. Anyway, this is compatible with the designer.

## OptionsDialog:

- Resizing was done in the designer. This is probably not compatible with the designer. I'll probably fix this.

### CODE REVIEW

**Comment by Baltasarq** [comment]
## OptionsDialog

Fixed. The resizing was done in the designer, and the minimum size was put in the OptionsDialog.cs file. This is totally compatible with the designer in the future.

**Comment by gbaychev** [comment]
Great, thank you once more!

**Comment by Baltasarq** [comment]
There is still a dialog missing: **PDFExportFinished**. The problem is that I'm unable to compile **NClass** anymore.

```
$ xbuild PDFExport/PDFExport.csproj
NClassFontResolver.cs(17,7): error CS0246: The type or namespace name 'PdfSharp' could not be found (are you missing a using directive or an assembly reference?)
...
PDFGraphics.cs(446,24): error CS0246: The type or namespace name 'XGraphicsPath' could not be found (are you missing a using directive or an assembly reference?)
PDFGraphics.cs(446,24): error CS0246: The type or namespace name 'XGraphicsPath' could not be found (are you missing a using directive or an assembly reference?)
```

It seems I'm missing **PDFSharp** (that did not happen before, I only have **NReflect**), and *X-something*. What do I have to do to have to include and how, in order to get the executable?

**Comment by gbaychev** [comment]
Yes, I needed to switch from PdfSharp to PDFsharp-gdi nuget package. You need to restore your nuget packages (at least of the PdfExport project), visual studio does this automatically, but I don't know if/which IDE you use.

**Comment by Baltasarq** [comment]
> Yes, I needed to switch from PdfSharp to PDFsharp-gdi nuget package. You need to restore your nuget packages (at least of the PdfExport project), visual studio does this automatically, but I don't know if/which IDE you use.

I fixed that installing nuget CLI and executing "nuget restore". Right now I am without IDE, since Rider has stopped working.

**Pull request merged**
